apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/proj1"